version: '3'
services:
  backend:
    build: .
    command: node src/index.js
    container_name: backend
    ports:
      - "1337:1337"
    # links:
    #   - service-db:service-db
    # depends_on:
    #   - postgres
    environment:
      NODE_ENV: production
      PORT: 1337
    networks:
      - nodenetwork

networks:
  nodenetwork:
    driver: bridge

volumes:
  node-data:
